// CSR/next-app-csr/src/app/error.tsx
'use client'; // Error components must be Client Components

import { useEffect } from 'react';
import Link from 'next/link';

interface ErrorPageProps {
  error: Error & { digest?: string };
  reset: () => void;
}

export default function Error({ error, reset }: ErrorPageProps) {
  useEffect(() => {
    // Log the error to an error reporting service
    console.error('Application error:', error);
  }, [error]);

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50">
      <div className="max-w-md w-full text-center px-4">
        {/* Error Icon */}
        <div className="mx-auto w-32 h-32 bg-gradient-to-br from-red-500 to-red-600 rounded-full flex items-center justify-center mb-8 shadow-lg">
          <svg className="w-16 h-16 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
        </div>
        
        {/* Error Content */}
        <h1 className="text-4xl font-bold text-gray-900 mb-4">Oops!</h1>
        <h2 className="text-2xl font-semibold text-gray-800 mb-4">Something went wrong</h2>
        <p className="text-gray-600 mb-8 leading-relaxed">
          We encountered an unexpected error while processing your request. 
          This issue has been logged and we're working to fix it.
        </p>
        
        {/* Error Details (only in development) */}
        {process.env.NODE_ENV === 'development' && (
          <div className="bg-red-50 border border-red-200 rounded-lg p-4 mb-8 text-left">
            <h3 className="text-sm font-semibold text-red-800 mb-2">Error Details:</h3>
            <p className="text-sm text-red-700 break-words">{error.message}</p>
            {error.digest && (
              <p className="text-xs text-red-600 mt-2">Error ID: {error.digest}</p>
            )}
          </div>
        )}
        
        {/* Action Buttons */}
        <div className="space-y-4">
          <button 
            onClick={reset}
            className="inline-block w-full bg-primary-600 hover:bg-primary-700 text-white font-semibold py-3 px-6 rounded-lg transition-colors duration-200"
          >
            Try Again
          </button>
          
          <Link 
            href="/"
            className="inline-block w-full border border-gray-300 hover:border-gray-400 text-gray-700 hover:text-gray-900 font-semibold py-3 px-6 rounded-lg transition-colors duration-200"
          >
            Go to Homepage
          </Link>
        </div>
        
        {/* Help Text */}
        <p className="text-sm text-gray-500 mt-8">
          If this problem persists, please <Link href="/#contact" className="text-primary-600 hover:text-primary-700 underline">contact our support team</Link>
        </p>
      </div>
    </div>
  );
}

// CSR/nuxt-app-csr/layouts/error.vue
<script lang="ts" setup>
const error = useError().value;

const goHome = () => {
	navigateTo('/');
	clearError();
};

const goBack = () => {
	if (window.history.length > 1) {
		window.history.back();
	} else {
		navigateTo('/');
	}
	clearError();
};
</script>

<template>
	<div class="error-wrap bg-gray-50">
		

		<main class="error-wrap__main relative flex-grow flex items-center justify-center px-4 sm:px-6 lg:px-8">
			<!-- Background Elements -->
			<div class="absolute inset-0 overflow-hidden">
				<div class="absolute -top-20 -right-20 w-96 h-96 bg-gradient-to-br from-blue-200/30 to-purple-200/30 rounded-full blur-3xl"></div>
				<div class="absolute -bottom-20 -left-20 w-96 h-96 bg-gradient-to-tr from-purple-200/30 to-blue-200/30 rounded-full blur-3xl"></div>
			</div>

			<div v-if="error" class="relative z-10 text-center max-w-2xl mx-auto">				<!-- Error Code with Gradient -->
				<div class="mb-8">
					<h1 class="mb-4 text-6xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent sm:text-7xl lg:text-8xl">
						{{ 'statusCode' in error ? error.statusCode : '500' }}
					</h1>
					<div class="w-24 h-1 bg-gradient-to-r from-blue-600 to-purple-600 mx-auto rounded-full"></div>
				</div>

				<!-- Error Message -->
				<div class="mb-12">
					<h2 class="mb-4 text-2xl font-semibold text-primary100 sm:text-3xl lg:text-4xl">
						{{ 'statusCode' in error && error.statusCode === 404 ? 'Page Not Found' : 'Something went wrong' }}
					</h2>
					<p class="text-lg leading-relaxed text-primary80 sm:text-xl">
						{{ 'statusCode' in error && error.statusCode === 404 
							? 'The page you\'re looking for doesn\'t exist. Please check the URL or return to the homepage.'
							: ('message' in error ? error.message : 'An unexpected error occurred. Please try again or return to the homepage.') }}
					</p>
				</div>

				<!-- Action Buttons -->
				<div class="flex flex-col sm:flex-row gap-4 justify-center">
					<button 
						@click="goHome"
						class="group inline-flex items-center px-8 py-4 bg-gradient-to-r from-blue-600 to-blue-700 text-white font-semibold rounded-lg hover:from-blue-700 hover:to-blue-800 transition-all duration-300 shadow-lg hover:shadow-xl transform hover:scale-105"
					>
						<svg class="mr-2 h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
						</svg>
						Go Home
					</button>
					<button 
						@click="goBack"
						class="border-2 border-blue-600 text-blue-600 px-8 py-4 rounded-lg font-semibold hover:bg-blue-600 hover:text-white transition-all duration-300"
					>
						<svg class="mr-2 h-5 w-5 inline" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
						</svg>
						Go Back
					</button>
				</div>				<!-- Additional Help Text -->
				<div class="mt-12 pt-8 border-t border-primary10">
					<p class="text-sm text-primary60">
						If this problem persists, please contact our support team.
					</p>
				</div>
			</div>
		</main>

		
	</div>
</template>
